branch-defaults:
  master:
    environment: Biosysdevdjango-env
    group_suffix: null
  oeh_production:
    environment: biosys-production
  oeh_uat:
    environment: biosys-uat
  production:
    environment: biosys-production
  slug_production:
    environment: biosys-production
  slug_uat:
    environment: biosys-uat
  staging:
    environment: biosys-staging
  uat:
    environment: biosys-uat
global:
  application_name: biosys
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
